SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES) TOTAL_SALES
FROM (
    SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES * PRICE SALES
    FROM BOOK
    JOIN AUTHOR
        ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    JOIN (
        SELECT BOOK_ID, SUM(SALES) SALES
        FROM BOOK_SALES
        WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
        GROUP BY BOOK_ID) SALES
        ON BOOK.BOOK_ID = SALES.BOOK_ID)
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
;