SELECT ANIMAL_ID, NAME
FROM (
    SELECT ROWNUM RN, ANIMAL_ID, NAME, PERIOD
    FROM (
        SELECT INS.ANIMAL_ID, OUTS.NAME, OUTS.DATETIME - INS.DATETIME PERIOD
        FROM ANIMAL_INS INS
        JOIN ANIMAL_OUTS OUTS
            ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
        ORDER BY PERIOD DESC))
WHERE RN <= 2
;