SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, RR.SCORE
FROM REST_INFO RI
JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID) RR
ON RI.REST_ID = RR.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC
;