SELECT YEAR, MONTH, GENDER, COUNT(*) USERS
FROM (
    SELECT
        DISTINCT(USER_ID) USER_ID,
        EXTRACT(YEAR FROM SALES_DATE) YEAR,
        EXTRACT(MONTH FROM SALES_DATE) MONTH
    FROM ONLINE_SALE) O
JOIN USER_INFO U
    ON O.USER_ID = U.USER_ID
        AND U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
;