SELECT O.PRODUCT_ID, P.PRODUCT_NAME, PRICE * AMOUNT TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
    GROUP BY PRODUCT_ID) O
LEFT JOIN FOOD_PRODUCT P
    ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID
;