SELECT FLAVOR
FROM (
    SELECT ROWNUM RN, FLAVOR, TOTAL
    FROM (
        SELECT FLAVOR, SUM(TOTAL) TOTAL
        FROM (
            SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
            FROM JULY
            GROUP BY FLAVOR
            UNION 
            SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
            FROM FIRST_HALF
            GROUP BY FLAVOR)
        GROUP BY FLAVOR
        ORDER BY TOTAL DESC))
WHERE RN <= 3
;