SELECT M.MEMBER_NAME, R.REVIEW_TEXT, 
    TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE M
    ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(COUNT(*)) COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID))
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
;