SELECT CAR.CAR_ID
FROM (
    SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'MM') = '10') HISTORY
JOIN CAR_RENTAL_COMPANY_CAR CAR
    ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE CAR.CAR_TYPE = '세단'
ORDER BY CAR.CAR_ID DESC
;